version: "3.9"

services:
  # dev environment, after this just do the copy thing
  nginx:
    container_name: nginx-tut
    build: ./nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/njs/:/etc/nginx/njs/
    ports:
      - 80:80
    depends_on:
      - flask

  flask:
    container_name: flask-dev
    build: ./server
    ports:
      - 5000:5000
